direction: right 

jld: INSPIRE JSON-LD data model

o: ohdsi
odb: ohdsi data base
a: athena voc server
daw: data analysis wb
code: R code
atlas: ATLAS: ohdsi UI
csv: source data

note: |md
# INSPIRE Meeting notes

* athena is a vocab server
* atlas ui hosted on AWS or others
* JOSN-LD helps address FAIR

|

csv -> omop -> odb

jld

odb  -> o 
a -> o 
o <-> daw -> code
# jld -> o : describes data integration flow
o -> ml : curated data with tags

r <- jld
ml <- jld 
